create table public.monthly_stats (
    id bigint generated by default as identity primary key,
    month text not null,
    views integer not null,
    watch_time integer not null,
    revenue integer not null,
    views_growth text,
    watch_time_growth text,
    revenue_growth text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add RLS policies
alter table public.monthly_stats enable row level security;

create policy "Enable read access for all users" on public.monthly_stats
    for select using (true);

create policy "Enable insert for authenticated users only" on public.monthly_stats
    for insert with check (auth.role() = 'authenticated');

create policy "Enable update for authenticated users only" on public.monthly_stats
    for update using (auth.role() = 'authenticated'); 